<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!--
    Sesto Esercizio
    nome: Erika
    cognome: Deboni
    nome del file: 06_esercizio.xml   
    descrizione:
    root: TEI
    Figli:
    - header(obbligatorio una volta sola)
    - facsimile(opzionale una volta sola)
    - testo(obbligatorio una o piu volte)
    * testo un mixed content con possibile elemento <seg>
    Attributi:
    - header: type:(fixed, CDATA "intestazione"); lang(opzionale,
    NMTOKEN)
    - facsimile: source:(obbligatorio); ref(optionale, IDREFS)
    - testo: id(obbligatorio, ID) type(opzionale contenuto testuale)
-->
<!DOCTYPE TEI [
<!ELEMENT TEI (header, facsimile?, text+)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT facsimile (#PCDATA)>
<!ELEMENT text (#PCDATA|seg)*>
<!ATTLIST header type CDATA #FIXED "intestazione">
<!ATTLIST header lang NMTOKEN #IMPLIED>
<!ATTLIST facsimile source CDATA #REQUIRED>
<!ATTLIST facsimile ref IDREFS #IMPLIED>
<!ATTLIST testo id ID #REQUIRED>
<!ATTLIST testo type CDATA #IMPLIED>
]>
<TEI>
    <header>header del documento</header>
    <facsimile source="facsimile01">fac-simile</facsimile>
    <text id="testo01">
    testo uno
    <seg>segue</seg>
    </text>
</TEI>
